version: '3.1'

services:

  drupal:
    image: drupal:9-php7.4-apache
    container_name: drupal
    restart: always
    ports:
      - "8200:80"
	volumes:
      - ./html:/var/www/html  
    depends_on:
      - drupaldb
    environment:
      HOST: drupaldb
      DBASE: drupal
      USER: user
      PASS: p4ssw0rd  
      
  drupaldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password 
    container_name: drupaldb 
	expose:
      - "3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupalpma 
    restart: always
    environment:
      PMA_HOST: drupaldb
      PMA_USER: user
      PMA_PASSWORD: p4ssw0rd
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"